language: rust
sudo: false

matrix:
  env:
    - BINARYEN=1.37.36
  include:
    # Test
    - rust: nightly
      before_install: rustup target add wasm32-unknown-unknown
      script: make test

    # WebAssembly
    - rust: nightly
      env: BUILD=release TARGET=wasm32-unknown-unknown
      before_install: rustup target add wasm32-unknown-unknown
      script: PATH=binaryen-$BINARYEN:$PATH make test-js

    # Linux
    - rust: nightly
      env: BUILD=release TARGET=x86_64-unknown-linux-musl
      install: true
      before_install: rustup target add $TARGET
      script: make test-c

    # macOS
    - os: osx
      rust: nightly
      env: BUILD=release MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
      install: true
      script: make test-c

before_script:
- |
  set -e

  cargo +nightly install clippy

  if [ -z "$TARGET" ] || [ "$TARGET" == wasm32-unknown-unknown ]; then
    cargo install wasm-bindgen-cli

    if [ "$BUILD" == release ]; then
      cargo install wasm-gc

      curl -O https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN/binaryen-$BINARYEN-x86-linux.tar.gz
      tar -x binaryen-*.tar.gz
    fi
  else
    cargo install cbindgen
  fi

install:
- |
  set -e

  if [ -z "$TARGET" ] || [ "$TARGET" == wasm32-unknown-unknown ]; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install 9
  fi

before_deploy:
- |
  set -e

  name="oxidation-tweek-$TRAVIS_TAG-$TARGET"
  mkdir $name

  if [ "$TARGET" == wasm32-unknown-unknown ]; then
    cp -R build/release/js/* $name/
  else
    cp target/$TARGET/release/liboxidation_tweek.dylib $name/
    cp README.md c/src/oxidation-tweek.h $name/
  fi

  tar czvf $name.tar.gz $name

deploy:
  api_key:
    secure: TODO
  file_glob: true
  file:
    - $name.tar.gz
  on:
    tags: true
  provider: releases
  skip_cleanup: true
