[package]
name = "rust-c-js"
version = "0.1.0"
authors = ["Mark Andrus Roberts <markandrusroberts@gmail.com>"]

[lib]
name = "rust_c_js"
crate-type = ["cdylib"]

[dependencies]
cfg-if = "0.1"
libc = "~0.2"
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = 's'
